In [241]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

partidas = pd.read_csv("./campeonato-brasileiro-full.csv")
cards = pd.read_csv("./campeonato-brasileiro-cartoes.csv")
gols = pd.read_csv("./campeonato-brasileiro-gols.csv")

partidas.head()

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
0,1,1,29/03/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ,NaN
1,2,1,29/03/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS,NaN
2,3,1,30/03/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR,NaN
3,4,1,30/03/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA,NaN
4,5,1,30/03/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP,NaN

In [242]:
partidas.tail()

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
9160,9160,38,07/12/2025,16:04,Santos,Cruzeiro,4-2-3-1,4-2-3-1,J. Vojvoda,T. Tite,Santos,"Estádio Urbano Caldeira, Santos",3,0,SP,MG,743978.75
9161,9161,38,07/12/2025,16:04,Sport,Gremio,5-4-1,4-2-3-1,C. de Lucena,L. Castro,Gremio,"Adelmar da Costa Carvalho, Recife",0,4,PE,RS,88755.00
9162,9163,38,07/12/2025,16:04,Botafogo-RJ,Fortaleza,4-2-3-1,4-4-2,Davide Ancelotti,Martin Palermo,Botafogo-RJ,"Estádio Nilton Santos, Rio de Janeiro",4,2,RJ,CE,905640.00
9163,9164,38,07/12/2025,16:04,Atletico-MG,Vasco,4-2-3-1,4-2-3-1,J. Sampaoli,F. Diniz,Atletico-MG,"Arena MRV, Belo Horizonte",5,0,MG,RJ,897255.52
9164,9165,38,07/12/2025,16:04,Internacional,Bragantino,4-4-2,4-2-3-1,R. Díaz,V. Mancini,Internacional,"Estádio Beira-Rio, Porto Alegre",3,1,RS,SP,1111157.00

In [243]:
partidas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9165 entries, 0 to 9164
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  9165 non-null   int64
 1   rodata              9165 non-null   int64
 2   data                9165 non-null   object
 3   hora                9165 non-null   object
 4   mandante            9165 non-null   object
 5   visitante           9165 non-null   object
 6   formacao_mandante   4190 non-null   object
 7   formacao_visitante  4190 non-null   object
 8   tecnico_mandante    4555 non-null   object
 9   tecnico_visitante   4555 non-null   object
 10  vencedor            9165 non-null   object
 11  arena               9165 non-null   object
 12  mandante_Placar     9165 non-null   int64
 13  visitante_Placar    9165 non-null   int64
 14  mandante_Estado     9165 non-null   object
 15  visitante_Estado    9165 non-null   object
 16  arrecadacao         380 non-null    float64
dtypes: float64(1), int64(4), object(12)
memory usage: 1.2+ MB

In [244]:
partidas.shape

(9165, 17)

In [245]:
# Converter data
partidas['data'] = pd.to_datetime(partidas['data'], format='%d/%m/%Y', errors='coerce')

# verificando a conversão 
print(f"Datas nulas após conversão: {partidas['data'].isna().sum()}")

Datas nulas após conversão: 0

In [246]:
# Meu interesse é em analisar apenas o campeonato brasileiro de 2025, então vou filtrar apenas este ano
df_2025 = partidas[partidas['data'].dt.year == 2025].copy()

print(f"Total de partidas em 2025: {len(df_2025)}")
print(f"Período: {df_2025['data'].min()} até {df_2025['data'].max()}")

Total de partidas em 2025: 380
Período: 2025-03-29 00:00:00 até 2025-12-07 00:00:00

In [247]:
# Verificar as colunas para compreender melhor o dataset 
df_2025.columns.tolist()

['ID',
 'rodata',
 'data',
 'hora',
 'mandante',
 'visitante',
 'formacao_mandante',
 'formacao_visitante',
 'tecnico_mandante',
 'tecnico_visitante',
 'vencedor',
 'arena',
 'mandante_Placar',
 'visitante_Placar',
 'mandante_Estado',
 'visitante_Estado',
 'arrecadacao']

In [248]:
# Varificar e tratar valores nulos
nulos = (df_2025.isnull().sum() / len(df_2025) * 100).round(2)
nulos[nulos > 0].sort_values(ascending=False)

Series([], dtype: float64)

In [249]:
df_2025.head(20)

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
8785,8786,1,2025-03-29,18:30,Juventude,Vitoria,4-2-3-1,4-2-3-1,M. Barbieri,J. Ventura,Juventude,"Alfredo Jaconi, Caxias do Sul",2,0,RS,BA,220000.00
8786,8787,1,2025-03-29,18:30,Fortaleza,Fluminense,3-4-3,4-3-3,T. Carpini,L. Luis Zubeldia,Fortaleza,"Arena Castelão, Fortaleza",2,0,CE,RJ,267643.00
8787,8790,1,2025-03-29,18:31,Cruzeiro,Mirassol,4-2-2-2,4-2-3-1,T. Tite,R. Guanaes,Cruzeiro,"Mineirão, Belo Horizonte",2,1,MG,SP,2089452.00
8788,8788,1,2025-03-29,18:32,Gremio,Atletico-MG,4-2-3-1,4-4-2,L. Castro,J. Sampaoli,Gremio,"Arena do Grêmio, Porto Alegre",2,1,RS,MG,1175509.00
8789,8789,1,2025-03-29,18:32,Sao Paulo,Sport,3-4-1-2,4-3-1-2,H. Crespo,C. de Lucena,-,"MorumBIS, São Paulo",0,0,SP,PE,2144747.00
8790,8791,1,2025-03-29,21:00,Flamengo,Internacional,4-4-2,4-2-3-1,F. Luís,R. Díaz,-,"Maracanã, Rio de Janeiro",1,1,RJ,RS,3150315.00
8791,8792,1,2025-03-30,16:01,Palmeiras,Botafogo-RJ,4-2-3-1,4-3-3,A. Ferreira,Renato Manuel Alves Paiva,-,"Allianz Parque, São Paulo",0,0,SP,RJ,2802427.70
8792,8793,1,2025-03-30,18:32,Vasco,Santos,4-2-3-1,4-2-3-1,F. Diniz,J. Vojvoda,Vasco,"Estádio São Januário, Rio de Janeiro",2,1,RJ,SP,1415049.00
8793,8794,1,2025-03-30,20:01,Bahia,Corinthians,4-2-3-1,4-3-3,R. Ceni,D. Junior,-,"Arena Fonte Nova, Salvador",1,1,BA,SP,1752529.00
8794,8795,1,2025-03-31,20:01,Bragantino,Ceara,4-2-3-1,4-2-3-1,V. Mancini,M. Mozart,-,"Nabizão, Bragança Paulista",2,2,SP,CE,61875.00
8795,8796,2,2025-04-05,18:31,Ceara,Gremio,4-2-3-1,4-2-3-1,M. Mozart,L. Castro,Ceara,"Arena Castelão, Fortaleza",2,0,CE,RS,472985.00
8796,8797,2,2025-04-05,18:31,Corinthians,Vasco,4-3-1-2,4-2-3-1,D. Junior,F. Diniz,Corinthians,"Neo Química Arena, São Paulo",3,0,SP,RJ,2958819.70
8797,8798,2,2025-04-05,21:01,Botafogo-RJ,Juventude,4-1-4-1,4-4-2,Renato Manuel Alves Paiva,Fabio Henrique Matias,Botafogo-RJ,"Estádio Nilton Santos, Rio de Janeiro",2,0,RJ,RS,555450.00
8798,8800,2,2025-04-06,16:00,Fluminense,Bragantino,4-2-3-1,4-2-3-1,L. Luis Zubeldia,V. Mancini,Fluminense,"Maracanã, Rio de Janeiro",2,1,RJ,SP,866231.50
8799,8799,2,2025-04-06,16:01,Atletico-MG,Sao Paulo,4-3-3,4-2-3-1,J. Sampaoli,H. Crespo,-,"Arena MRV, Belo Horizonte",0,0,MG,SP,1507606.50
8800,8802,2,2025-04-06,18:30,Mirassol,Fortaleza,4-2-3-1,4-2-3-1,R. Guanaes,T. Carpini,-,"Campos Maia, Mirassol",1,1,SP,CE,113360.00
8801,8803,2,2025-04-06,18:31,Vitoria,Flamengo,4-2-3-1,4-2-3-1,J. Ventura,F. Luís,Flamengo,"Barradão, Salvador",1,2,BA,RJ,1117870.00
8802,8804,2,2025-04-06,18:31,Sport,Palmeiras,4-5-1,3-4-2-1,C. de Lucena,A. Ferreira,Palmeiras,"Adelmar da Costa Carvalho, Recife",1,2,PE,SP,1577490.00
8803,8801,2,2025-04-06,18:32,Internacional,Cruzeiro,4-2-3-1,4-3-3,R. Díaz,T. Tite,Internacional,"Estádio Beira-Rio, Porto Alegre",3,0,RS,MG,1628212.00
8804,8805,2,2025-04-06,20:32,Santos,Bahia,4-2-3-1,4-3-3,J. Vojvoda,R. Ceni,-,"Estádio Urbano Caldeira, Santos",2,2,SP,BA,499201.25

In [250]:
df_2025 = df_2025.rename(columns={
    'mandante_Placar': 'gols_mandante',
    'visitante_Placar': 'gols_visitante',
    'rodata': 'rodada'
})

In [251]:
df_2025.head()

,ID,rodada,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,gols_mandante,gols_visitante,mandante_Estado,visitante_Estado,arrecadacao
8785,8786,1,2025-03-29,18:30,Juventude,Vitoria,4-2-3-1,4-2-3-1,M. Barbieri,J. Ventura,Juventude,"Alfredo Jaconi, Caxias do Sul",2,0,RS,BA,220000.0
8786,8787,1,2025-03-29,18:30,Fortaleza,Fluminense,3-4-3,4-3-3,T. Carpini,L. Luis Zubeldia,Fortaleza,"Arena Castelão, Fortaleza",2,0,CE,RJ,267643.0
8787,8790,1,2025-03-29,18:31,Cruzeiro,Mirassol,4-2-2-2,4-2-3-1,T. Tite,R. Guanaes,Cruzeiro,"Mineirão, Belo Horizonte",2,1,MG,SP,2089452.0
8788,8788,1,2025-03-29,18:32,Gremio,Atletico-MG,4-2-3-1,4-4-2,L. Castro,J. Sampaoli,Gremio,"Arena do Grêmio, Porto Alegre",2,1,RS,MG,1175509.0
8789,8789,1,2025-03-29,18:32,Sao Paulo,Sport,3-4-1-2,4-3-1-2,H. Crespo,C. de Lucena,-,"MorumBIS, São Paulo",0,0,SP,PE,2144747.0

In [252]:
# Total de gols na partida
df_2025['total_gols'] = df_2025['gols_mandante'] + df_2025['gols_visitante']

In [253]:
# Saldo de gols (mandante)
df_2025['saldo_gols'] = df_2025['gols_mandante'] - df_2025['gols_visitante']

In [254]:
df_2025['mes'] = df_2025['data'].dt.month

In [255]:
print(df_2025[['gols_mandante', 'gols_visitante', 'total_gols']].describe())

#max gols_mandantes Flamengo 8 x 0 Vitória 25 de agosto
#max gols_visitante Santos 0 x 6 Vasco 17 de agosto

       gols_mandante  gols_visitante  total_gols
count     380.000000      380.000000  380.000000
mean        1.526316        0.997368    2.523684
std         1.258991        1.028611    1.546796
min         0.000000        0.000000    0.000000
25%         1.000000        0.000000    1.000000
50%         1.000000        1.000000    2.000000
75%         2.000000        2.000000    3.000000
max         8.000000        6.000000    8.000000

In [256]:
print(f'Linhas duplicadas: {df_2025.duplicated(subset=['data', 'mandante', 'visitante']).sum()}')

Linhas duplicadas: 0

In [257]:
df_2025.to_csv('c:/Projetos/analise-campeonato-brasileiro/brasileirao_2025_limpo.csv', index=False)

In [258]:
# Quantidade de partidas cada arena teve em 2025
df_2025['arena'].value_counts(dropna=False)

arena
Maracanã, Rio de Janeiro                                        39
Arena Castelão, Fortaleza                                       37
Estádio Urbano Caldeira, Santos                                 22
Allianz Parque, São Paulo                                       19
Arena do Grêmio, Porto Alegre                                   19
Arena Fonte Nova, Salvador                                      19
Alfredo Jaconi, Caxias do Sul                                   19
Estádio Beira-Rio, Porto Alegre                                 19
Barradão, Salvador                                              19
Arena MRV, Belo Horizonte                                       19
Neo Química Arena, São Paulo                                    19
Campos Maia, Mirassol                                           19
Estádio Nilton Santos, Rio de Janeiro                           19
Adelmar da Costa Carvalho, Recife                               19
Mineirão, Belo Horizonte                                        18
Estádio Municipal Cicero De Souza Marques, Bragança Paulista    16
Estádio São Januário, Rio de Janeiro                            16
MorumBIS, São Paulo                                             15
Nabizão, Bragança Paulista                                       3
Mané Garrincha, Brasília                                         2
Estádio Parque do Sabiá, Uberlândia                              1
Estádio Presidente Vargas, Fortaleza                             1
Arena Barueri, Barueri                                           1
Name: count, dtype: int64

In [259]:
# Resultado da partida 
def classificar(gols_a, gols_b):
    if gols_a > gols_b:
        return 'Vitória'
    elif gols_a < gols_b:
        return 'Derrota'
    return 'Empate'

df_2025['resultado_mandante'] = df_2025.apply(
    lambda row: classificar(row['gols_mandante'], row['gols_visitante']), axis=1
)

df_2025['resultado_visitante'] = df_2025.apply(
    lambda row: classificar(row['gols_visitante'], row['gols_mandante']), axis=1
)

In [260]:
df_mandante = df_2025[[
    'data', 'rodada', 'mandante', 'tecnico_mandante',
    'gols_mandante', 'gols_visitante', 'resultado_mandante'
]].copy()

df_mandante.columns = ['data', 'rodada', 'time', 'tecnico', 'gols_pro', 'gols_contra', 'resultado']
df_mandante['mando'] = 'Casa'

df_mandante.head(20)

,data,rodada,time,tecnico,gols_pro,gols_contra,resultado,mando
8785,2025-03-29,1,Juventude,M. Barbieri,2,0,Vitória,Casa
8786,2025-03-29,1,Fortaleza,T. Carpini,2,0,Vitória,Casa
8787,2025-03-29,1,Cruzeiro,T. Tite,2,1,Vitória,Casa
8788,2025-03-29,1,Gremio,L. Castro,2,1,Vitória,Casa
8789,2025-03-29,1,Sao Paulo,H. Crespo,0,0,Empate,Casa
8790,2025-03-29,1,Flamengo,F. Luís,1,1,Empate,Casa
8791,2025-03-30,1,Palmeiras,A. Ferreira,0,0,Empate,Casa
8792,2025-03-30,1,Vasco,F. Diniz,2,1,Vitória,Casa
8793,2025-03-30,1,Bahia,R. Ceni,1,1,Empate,Casa
8794,2025-03-31,1,Bragantino,V. Mancini,2,2,Empate,Casa
8795,2025-04-05,2,Ceara,M. Mozart,2,0,Vitória,Casa
8796,2025-04-05,2,Corinthians,D. Junior,3,0,Vitória,Casa
8797,2025-04-05,2,Botafogo-RJ,Renato Manuel Alves Paiva,2,0,Vitória,Casa
8798,2025-04-06,2,Fluminense,L. Luis Zubeldia,2,1,Vitória,Casa
8799,2025-04-06,2,Atletico-MG,J. Sampaoli,0,0,Empate,Casa
8800,2025-04-06,2,Mirassol,R. Guanaes,1,1,Empate,Casa
8801,2025-04-06,2,Vitoria,J. Ventura,1,2,Derrota,Casa
8802,2025-04-06,2,Sport,C. de Lucena,1,2,Derrota,Casa
8803,2025-04-06,2,Internacional,R. Díaz,3,0,Vitória,Casa
8804,2025-04-06,2,Santos,J. Vojvoda,2,2,Empate,Casa

In [261]:
df_visitante = df_2025[[
    'data', 'rodada', 'visitante', 'tecnico_visitante',
    'gols_visitante', 'gols_mandante', 'resultado_visitante'
]].copy()

df_visitante.columns = ['data', 'rodada', 'time', 'tecnico', 'gols_pro', 'gols_contra', 'resultado']
df_visitante['mando'] = 'Fora'

df_visitante.head(20)

,data,rodada,time,tecnico,gols_pro,gols_contra,resultado,mando
8785,2025-03-29,1,Vitoria,J. Ventura,0,2,Derrota,Fora
8786,2025-03-29,1,Fluminense,L. Luis Zubeldia,0,2,Derrota,Fora
8787,2025-03-29,1,Mirassol,R. Guanaes,1,2,Derrota,Fora
8788,2025-03-29,1,Atletico-MG,J. Sampaoli,1,2,Derrota,Fora
8789,2025-03-29,1,Sport,C. de Lucena,0,0,Empate,Fora
8790,2025-03-29,1,Internacional,R. Díaz,1,1,Empate,Fora
8791,2025-03-30,1,Botafogo-RJ,Renato Manuel Alves Paiva,0,0,Empate,Fora
8792,2025-03-30,1,Santos,J. Vojvoda,1,2,Derrota,Fora
8793,2025-03-30,1,Corinthians,D. Junior,1,1,Empate,Fora
8794,2025-03-31,1,Ceara,M. Mozart,2,2,Empate,Fora
8795,2025-04-05,2,Gremio,L. Castro,0,2,Derrota,Fora
8796,2025-04-05,2,Vasco,F. Diniz,0,3,Derrota,Fora
8797,2025-04-05,2,Juventude,Fabio Henrique Matias,0,2,Derrota,Fora
8798,2025-04-06,2,Bragantino,V. Mancini,1,2,Derrota,Fora
8799,2025-04-06,2,Sao Paulo,H. Crespo,0,0,Empate,Fora
8800,2025-04-06,2,Fortaleza,T. Carpini,1,1,Empate,Fora
8801,2025-04-06,2,Flamengo,F. Luís,2,1,Vitória,Fora
8802,2025-04-06,2,Palmeiras,A. Ferreira,2,1,Vitória,Fora
8803,2025-04-06,2,Cruzeiro,T. Tite,0,3,Derrota,Fora
8804,2025-04-06,2,Bahia,R. Ceni,2,2,Empate,Fora